Added JSON return to List Indices and Logs
paynejacob/rancher-logging-examples pull request #10
Opened 2021-06-12 10:21 UTC by MrSupiri

2021-06-14 15:37 UTC, paynejacob requested changes

2021-06-14 15:37 UTC, paynejacob commented on log-output/pkg/index/service.go
> +			for _, log := range s.indices[indexName].Logs {
Can you copy logs out into a variable so we don't block for the json unmarshall?

2021-06-14 15:37 UTC, paynejacob commented on log-output/pkg/index/service.go
> +		if _, exists := s.indices[indexName]; exists {
This logic can be reused and moved out of the if block

2021-06-14 15:37 UTC, paynejacob commented on log-output/pkg/index/service.go
> +		json.NewEncoder(w).Encode(indices)
nit: can you add `_ =`, I like to call out that we are explicitly ignoring an error.

2021-06-14 15:37 UTC, paynejacob commented on log-output/pkg/index/index.go
> +	Path     string    `json:"path"`
What does this adding this get us? it is not a full url so clients will need to do formatting on their end anyway.

2021-06-17 18:03 UTC, paynejacob commented
@MrSupiri it looks like the build failed but the validation script gave a false positive.  Can you correct the build issue?

2021-06-20 12:07 UTC, MrSupiri commented
Sorry about that, I found and fixed the issue and re-ran those tests. It should work now

2021-06-21 15:58 UTC, paynejacob approved these changes

2021-06-21 15:58 UTC, merged