Updated Makefile to work on Linux
paynejacob/rancher-logging-examples pull request #8
Opened 2021-06-01 12:35 UTC by MrSupiri

Makefile given in the repo doesn't work on Linux so I added a platform check to `port-forward` rule and depending on that switched method used to start the webpage and also removed what seems to be a typo on `install` rule. 

I have tested this only on Linux, I am 98% sure this will work on Darwin but I am not so positive on Windows so give it a test before merging.

2021-06-01 16:29 UTC, nickgerace requested changes

2021-06-01 16:29 UTC, nickgerace commented on Makefile
> +UNAME_S := $(shell uname -s)
nit: can you make this match style? `FOO:=BAR`

2021-06-01 16:29 UTC, nickgerace commented on Makefile
> +install:
The typo here was that this should have a target dependency on `uninstall` and not `uninstall-example`. Would you mind adding `uninstall` as a target dependency?

2021-06-01 16:29 UTC, nickgerace commented on Makefile
> +	- kubectl delete namespace $(NAMESPACE)
What does this change do? We use the `-$COMMAND` notation to ignore errors. This is done since uninstallation should be allowed to fail if the chart is already uninstalled.

2021-06-01 16:29 UTC, nickgerace commented on Makefile
> +endif
This was also a typo and should be its own target unrelated to `port-foward`. May you create a new target called `open`, `open-log-output`, or something else you would prefer?

2021-06-02 07:27 UTC, MrSupiri commented on Makefile
> +endif
ok I added `open-log-output` as rule

2021-06-02 16:30 UTC, nickgerace commented
LGTM, will approve once squashed. Thank you!

2021-06-03 16:17 UTC, paynejacob approved these changes

2021-06-03 16:18 UTC, merged